title: 八股文笔记
theme: minima

# 告诉 Jekyll 所有 _xxx collection 都放在 notes/ 目录下
collections_dir: notes

collections:
  embedded:
    output: true
    permalink: /embedded/:path/
  software:
    output: true
    permalink: /software/:path/
  gpu_cuda:
    output: true
    permalink: /gpu-cuda/:path/
  algorithms:
    output: true
    permalink: /algorithms/:path/
  mbd:
    output: true
    permalink: /mbd/:path/

# 其余配置保持不变……


# 默认把 head.html 注入到所有页面的 <head>
defaults:
  - scope:
      path: ""
    values:
      includes:
        - head.html

