title: 八股文笔记
theme: minima

# Jekyll Collections（如果之前已配置可保留）
collections:
  embedded:
    output: true
    permalink: /embedded/:path/
  software:
    output: true
    permalink: /software/:path/
  gpu_cuda:
    output: true
    permalink: /gpu-cuda/:path/
  algorithms:
    output: true
    permalink: /algorithms/:path/
  mbd:
    output: true
    permalink: /MBD/:path/


# 默认把 head.html 注入到所有页面的 <head>
defaults:
  - scope:
      path: ""
    values:
      includes:
        - head.html

