title: K1n's blog
description: "K1n's blog"
url: "https://blog.k1n.asia"
baseurl: ""
author: kin


encoding: "utf-8"


kramdown:
  syntax_highlighter_opts:
    disable : true



# Google Analytics 4 配置（留空则不注入脚本）
ga4_measurement_id: G-WNZR555V1D