title: 八股文笔记
description: "嵌入式 / CUDA / 多体动力学 / 面试记录"
url: "https://blog.k1n.asia"     # 自定义域名 ✅
baseurl: ""                      # 设置为空 ✅


# 1. 如果需要在 Markdown 内用相对 .md 链接，启用这个插件（可选）
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - CODE_OF_CONDUCT.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

collections:
  embedded:
    output: true
    permalink: /embedded/:path/
  software:
    output: true
    permalink: /software/:path/
  gpu_cuda:
    output: true
    permalink: /gpu-cuda/:path/
  algorithms:
    output: true
    permalink: /algorithms/:path/
  mbd:
    output: true
    permalink: /software/:path/

# ———————— 在这里新增 ————————


# 2. 默认所有 .md 文件都使用 default 布局（即使没写 Front Matter）
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
    values:
      includes:
        - head.html


## ———————— 新增结束 ————————

## 其余配置保持不变……
